name: sofo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  loading_animation_widget: ^1.3.0
  pdf: ^3.11.3
  printing: ^5.14.2
  open_file: ^3.5.10
  geolocator: ^8.0.2
  geocoding: ^2.0.5
  google_maps_flutter: ^2.10.1
  multi_select_flutter: ^4.1.3
  image_picker: any
  



  cached_network_image: ^3.4.1
  # upi_india: ^3.0.1
  # quantupi: ^0.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^5.0.0

dependency_overrides:
  geolocator_android: 4.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

